server:
  port: 8000
  servlet: 
    context-path: /f1

spring:
  datasource: 
    username: admin
    password: 550f1proj
    url: jdbc:mysql://f1db.cnjnxpope1ps.us-east-1.rds.amazonaws.com:3306/f1_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    # jdbc:mysql://localhost:3306/cis550?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  
logging:
  level:
    edu.upenn.cis550.f1project: debug
